#!/bin/bash
#PBS -q normal
#PBS -j oe
#PBS -l walltime=00:05:00
#PBS -l select=1:ncpus=1:mem=256M
#PBS -P 21126683
#PBS -N WriteDataTestJob

cd ${PBS_O_WORKDIR}

module load singularity

singularity exec /home/users/industry/rolos/alexeyk/scratch/test/singularity/inc5654.img python --version
singularity exec /home/users/industry/rolos/alexeyk/scratch/test/singularity/inc5654.img python write_data.py
